"""按平台节奏执行推送。

用法:
    # 直接运行（按配置决定当前小时需要发哪些平台）
    python hourly_bot.py

    # 只抓 X
    python hourly_bot.py --only x

    # 忽略节奏限制，当前小时强制检查全部平台
    python hourly_bot.py --force

Windows 定时任务设置:
    schtasks /create /tn "AI-Daily-Hourly" /tr "python D:\\code\\self-project\\feishu-feed-test\\hourly_bot.py" /sc hourly
"""
import argparse
import json
import sys
from datetime import datetime, timedelta, timezone

from delivery import (
    due_platform_keys,
    filter_recent_articles,
    get_delivery_config,
    load_delivery_state,
    mark_sent_articles,
    save_delivery_state,
)
from fetcher import fetch_hn, fetch_reddit, fetch_x
from sender import WEBHOOK_URL, build_ai_daily_card, send_card
from summarizer import summarize

PLATFORM_FETCHERS = {
    "x": fetch_x,
    "reddit": fetch_reddit,
    "hn": fetch_hn,
}


def run_platform(
    platform_key: str,
    now_utc: datetime,
    state: dict[str, dict[str, str]],
    dry_run: bool,
) -> None:
    config = get_delivery_config(platform_key)
    fetch_fn = PLATFORM_FETCHERS[platform_key]
    cn_tz = timezone(timedelta(hours=8))

    print(f"\n{'='*40}")
    print(
        f"Step: fetcher -> {config.platform} "
        f"(fetch last {config.fetch_hours}h, cadence {config.cadence_hours}h)"
    )
    print(f"{'='*40}")
    articles = fetch_fn(hours=config.fetch_hours)
    print(f"Fetched {len(articles)} articles")

    filtered_articles = filter_recent_articles(
        state=state,
        platform_key=platform_key,
        articles=articles,
        now=now_utc,
        dedupe_hours=config.dedupe_hours,
    )
    print(f"After send-history filter: {len(filtered_articles)} articles")

    if len(filtered_articles) < config.min_articles:
        print(
            f"\nToo few articles ({len(filtered_articles)} < {config.min_articles}). "
            "Skipping this run."
        )
        return

    print(f"\n{'='*40}")
    print("Step: summarizer -> categories")
    print(f"{'='*40}")
    categories = summarize(filtered_articles, platform=config.platform)
    item_total = sum(len(c.get("items", [])) for c in categories)
    print(f"Generated {len(categories)} categories, {item_total} items total")

    if item_total == 0:
        print("\nNo items generated by summarizer. Skipping this run.")
        return

    print(f"\n{'='*40}")
    print("Step: card_builder -> payload")
    print(f"{'='*40}")
    start_time_utc = now_utc - timedelta(hours=config.fetch_hours)
    payload = build_ai_daily_card(
        categories,
        platform=config.platform,
        start_time=start_time_utc.astimezone(cn_tz),
        end_time=now_utc.astimezone(cn_tz),
    )

    preview_path = f"tmp/hourly_bot_{platform_key}_preview.json"
    with open(preview_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    print(f"Preview saved to: {preview_path}")

    if dry_run:
        print("\nDry run mode — card NOT sent.")
        return

    print(f"\n{'='*40}")
    print("Step: send_card -> Feishu")
    print(f"{'='*40}")
    if not WEBHOOK_URL:
        print("Error: FEISHU_WEBHOOK_URL not configured")
        return

    result = send_card(WEBHOOK_URL, payload)
    print(f"Success: {result}")
    mark_sent_articles(state, platform_key, filtered_articles, now_utc)


def main():
    parser = argparse.ArgumentParser(description="AI 资讯按平台节奏推送")
    parser.add_argument(
        "--only",
        choices=["x", "reddit", "hn", "all"],
        default="all",
        help="只抓某个平台 (默认 all)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="忽略平台节奏限制，当前小时强制运行选中的平台",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="只生成预览，不发 Feishu",
    )
    args = parser.parse_args()

    sys.stdout.reconfigure(encoding="utf-8")
    utc_now = datetime.now(timezone.utc)
    cn_tz = timezone(timedelta(hours=8))
    now_cn = utc_now.astimezone(cn_tz)

    if args.only == "all":
        selected_keys = list(PLATFORM_FETCHERS.keys())
        if not args.force:
            due_keys = set(due_platform_keys(now_cn))
            selected_keys = [key for key in selected_keys if key in due_keys]
            print(
                f"Current CN hour: {now_cn.strftime('%Y-%m-%d %H:%M')}, "
                f"due platforms: {', '.join(selected_keys) or 'none'}"
            )
    else:
        selected_keys = [args.only]

    if not selected_keys:
        print("\nNo platforms due in this run. Exiting.")
        return

    state = load_delivery_state()
    for platform_key in selected_keys:
        run_platform(
            platform_key=platform_key,
            now_utc=utc_now,
            state=state,
            dry_run=args.dry_run,
        )
    save_delivery_state(state)


if __name__ == "__main__":
    main()
